const baseURL = "https://wordpress.ramesh.no/wp-json/wp/v2/";
const endpoint = "posts";
const fetchedURL = baseURL + endpoint;

export const fetchPostData = async () => {
    return await fetch(`${fetchedURL}?_embed&per_page=100`)
        .then((res) => res.json())
        .then((res) => {
            return res.map((post) => {
                if (
                    post._embedded &&
                    post._embedded["wp:featuredmedia"] &&
                    post._embedded["wp:featuredmedia"][0]
                ) {
                    return {
                        ...post,
                        title: post.title.rendered,
                        excerpt: post.excerpt.rendered,
                        image: post._embedded["wp:featuredmedia"][0].source_url,
                    };
                }
                return {
                    ...post,
                    title: post.title.rendered,
                    excerpt: post.excerpt.rendered,
                    image: "",
                };
            });
        });
};

export const fetchAnotherData = () => {
    return [
        {
            image: "../../assets/codeone.jpg",
            date: "Tuesday, 11pm, EST 2024.01.24,",
            title:
                "This is going to the box heading we will have same size like top.",
            post: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores qui nam ratione sed fuga, tenetur minus, cumque praesentium dolorem numquam illo aliquam nostrum quod facilis vero voluptatem ex optio explicabo molestias! Unde id nemo consequatur culpa minus deleniti adipisci alias necessitatibus veniam asperiores repellendus ipsum ex ea, qui architecto provident ipsam totam quasi. Accusamus ullam voluptatibus aliquam voluptatum hic animi, quibusdam vero, deserunt, impedit quos facilis deleniti vel cumque ipsum maiores. Natus laudantium in laboriosam consequatur magni non possimus id impedit, aspernatur totam saepe perferendis provident incidunt nihil optio ratione porro dolor, praesentium numquam alias perspiciatis at. Incidunt aliquid cupiditate repellat deserunt expedita odio cumque, tempora impedit minus, consequatur laboriosam necessitatibus ullam reprehenderit sed minima dicta ipsam ex atque eveniet excepturi aperiam possimus. Debitis delectus nobis fugit cum repellat dolores nisi soluta, magnam, deleniti harum ratione suscipit deserunt porro. Minima natus commodi voluptatibus at ducimus debitis expedita velit sint aliquam vitae explicabo voluptate reprehenderit adipisci porro, eum repellat voluptatem autem. Est aperiam excepturi eos, dolorem, hic reiciendis sunt voluptatibus veniam repellendus blanditiis expedita, earum ullam dolor quisquam consectetur facere optio praesentium. Est cumque tenetur quae doloribus libero laudantium quod illum a ut. Minus tempore, incidunt quae ipsam temporibus debitis vero necessitatibus placeat doloremque, ea cum delectus nam distinctio officiis numquam architecto sed consectetur quibusdam. Ad quia minima itaque sit perspiciatis saepe earum accusantium veniam a sunt, deleniti odio incidunt fugit. Officia atque facilis odio exercitationem amet harum reiciendis a id quos quibusdam! Ut at neque, quasi est reprehenderit blanditiis doloremque eum esse quibusdam incidunt rem eligendi facere, quis placeat amet voluptatibus consequatur similique commodi sunt eveniet. Doloribus delectus id beatae officiis numquam ipsam dicta, eveniet ducimus? Quia excepturi quis rem quasi iusto. Iste repellendus officiis eum fugiat neque ipsum, dignissimos saepe placeat doloribus necessitatibus fugit sunt, eaque debitis quisquam unde!",
            author: "little soldier",
        },
        {
            image: "../../assets/relaxcode.jpg",
            date: "Tuesday, 11pm, EST 2024.01.24,",
            title:
                "This is going to the box heading we will have same size like top.",
            post: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores qui nam ratione sed fuga, tenetur minus, cumque praesentium dolorem numquam illo aliquam nostrum quod facilis vero voluptatem ex optio explicabo molestias! Unde id nemo consequatur culpa minus deleniti adipisci alias necessitatibus veniam asperiores repellendus ipsum ex ea, qui architecto provident ipsam totam quasi. Accusamus ullam voluptatibus aliquam voluptatum hic animi, quibusdam vero, deserunt, impedit quos facilis deleniti vel cumque ipsum maiores. Natus laudantium in laboriosam consequatur magni non possimus id impedit, aspernatur totam saepe perferendis provident incidunt nihil optio ratione porro dolor, praesentium numquam alias perspiciatis at. Incidunt aliquid cupiditate repellat deserunt expedita odio cumque, tempora impedit minus, consequatur laboriosam necessitatibus ullam reprehenderit sed minima dicta ipsam ex atque eveniet excepturi aperiam possimus. Debitis delectus nobis fugit cum repellat dolores nisi soluta, magnam, deleniti harum ratione suscipit deserunt porro. Minima natus commodi voluptatibus at ducimus debitis expedita velit sint aliquam vitae explicabo voluptate reprehenderit adipisci porro, eum repellat voluptatem autem. Est aperiam excepturi eos, dolorem, hic reiciendis sunt voluptatibus veniam repellendus blanditiis expedita, earum ullam dolor quisquam consectetur facere optio praesentium. Est cumque tenetur quae doloribus libero laudantium quod illum a ut. Minus tempore, incidunt quae ipsam temporibus debitis vero necessitatibus placeat doloremque, ea cum delectus nam distinctio officiis numquam architecto sed consectetur quibusdam. Ad quia minima itaque sit perspiciatis saepe earum accusantium veniam a sunt, deleniti odio incidunt fugit. Officia atque facilis odio exercitationem amet harum reiciendis a id quos quibusdam! Ut at neque, quasi est reprehenderit blanditiis doloremque eum esse quibusdam incidunt rem eligendi facere, quis placeat amet voluptatibus consequatur similique commodi sunt eveniet. Doloribus delectus id beatae officiis numquam ipsam dicta, eveniet ducimus? Quia excepturi quis rem quasi iusto. Iste repellendus officiis eum fugiat neque ipsum, dignissimos saepe placeat doloribus necessitatibus fugit sunt, eaque debitis quisquam unde!",
            author: "little soldier",
        },
        {
            image: "../../assets/Rectangle 6.png",
            date: "Tuesday, 11pm, EST 2024.01.24,",
            title:
                "This is going to the box heading we will have same size like top.",
            post: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores qui nam ratione sed fuga, tenetur minus, cumque praesentium dolorem numquam illo aliquam nostrum quod facilis vero voluptatem ex optio explicabo molestias! Unde id nemo consequatur culpa minus deleniti adipisci alias necessitatibus veniam asperiores repellendus ipsum ex ea, qui architecto provident ipsam totam quasi. Accusamus ullam voluptatibus aliquam voluptatum hic animi, quibusdam vero, deserunt, impedit quos facilis deleniti vel cumque ipsum maiores. Natus laudantium in laboriosam consequatur magni non possimus id impedit, aspernatur totam saepe perferendis provident incidunt nihil optio ratione porro dolor, praesentium numquam alias perspiciatis at. Incidunt aliquid cupiditate repellat deserunt expedita odio cumque, tempora impedit minus, consequatur laboriosam necessitatibus ullam reprehenderit sed minima dicta ipsam ex atque eveniet excepturi aperiam possimus. Debitis delectus nobis fugit cum repellat dolores nisi soluta, magnam, deleniti harum ratione suscipit deserunt porro. Minima natus commodi voluptatibus at ducimus debitis expedita velit sint aliquam vitae explicabo voluptate reprehenderit adipisci porro, eum repellat voluptatem autem. Est aperiam excepturi eos, dolorem, hic reiciendis sunt voluptatibus veniam repellendus blanditiis expedita, earum ullam dolor quisquam consectetur facere optio praesentium. Est cumque tenetur quae doloribus libero laudantium quod illum a ut. Minus tempore, incidunt quae ipsam temporibus debitis vero necessitatibus placeat doloremque, ea cum delectus nam distinctio officiis numquam architecto sed consectetur quibusdam. Ad quia minima itaque sit perspiciatis saepe earum accusantium veniam a sunt, deleniti odio incidunt fugit. Officia atque facilis odio exercitationem amet harum reiciendis a id quos quibusdam! Ut at neque, quasi est reprehenderit blanditiis doloremque eum esse quibusdam incidunt rem eligendi facere, quis placeat amet voluptatibus consequatur similique commodi sunt eveniet. Doloribus delectus id beatae officiis numquam ipsam dicta, eveniet ducimus? Quia excepturi quis rem quasi iusto. Iste repellendus officiis eum fugiat neque ipsum, dignissimos saepe placeat doloribus necessitatibus fugit sunt, eaque debitis quisquam unde!",
            author: "Ramesh",
        },
        {
            image: "../../assets/Rectangle 6.png",
            date: "Tuesday, 11pm, EST 2024.01.24,",
            title:
                "This is going to the box heading we will have same size like top.",
            post: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores qui nam ratione sed fuga, tenetur minus, cumque praesentium dolorem numquam illo aliquam nostrum quod facilis vero voluptatem ex optio explicabo molestias! Unde id nemo consequatur culpa minus deleniti adipisci alias necessitatibus veniam asperiores repellendus ipsum ex ea, qui architecto provident ipsam totam quasi. Accusamus ullam voluptatibus aliquam voluptatum hic animi, quibusdam vero, deserunt, impedit quos facilis deleniti vel cumque ipsum maiores. Natus laudantium in laboriosam consequatur magni non possimus id impedit, aspernatur totam saepe perferendis provident incidunt nihil optio ratione porro dolor, praesentium numquam alias perspiciatis at. Incidunt aliquid cupiditate repellat deserunt expedita odio cumque, tempora impedit minus, consequatur laboriosam necessitatibus ullam reprehenderit sed minima dicta ipsam ex atque eveniet excepturi aperiam possimus. Debitis delectus nobis fugit cum repellat dolores nisi soluta, magnam, deleniti harum ratione suscipit deserunt porro. Minima natus commodi voluptatibus at ducimus debitis expedita velit sint aliquam vitae explicabo voluptate reprehenderit adipisci porro, eum repellat voluptatem autem. Est aperiam excepturi eos, dolorem, hic reiciendis sunt voluptatibus veniam repellendus blanditiis expedita, earum ullam dolor quisquam consectetur facere optio praesentium. Est cumque tenetur quae doloribus libero laudantium quod illum a ut. Minus tempore, incidunt quae ipsam temporibus debitis vero necessitatibus placeat doloremque, ea cum delectus nam distinctio officiis numquam architecto sed consectetur quibusdam. Ad quia minima itaque sit perspiciatis saepe earum accusantium veniam a sunt, deleniti odio incidunt fugit. Officia atque facilis odio exercitationem amet harum reiciendis a id quos quibusdam! Ut at neque, quasi est reprehenderit blanditiis doloremque eum esse quibusdam incidunt rem eligendi facere, quis placeat amet voluptatibus consequatur similique commodi sunt eveniet. Doloribus delectus id beatae officiis numquam ipsam dicta, eveniet ducimus? Quia excepturi quis rem quasi iusto. Iste repellendus officiis eum fugiat neque ipsum, dignissimos saepe placeat doloribus necessitatibus fugit sunt, eaque debitis quisquam unde!",
            author: "Joy",
        },
        {
            image: "../../assets/Rectangle 6.png",
            date: "Tuesday, 11pm, EST 2024.01.24,",
            title:
                "This is going to the box heading we will have same size like top.",
            post: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores qui nam ratione sed fuga, tenetur minus, cumque praesentium dolorem numquam illo aliquam nostrum quod facilis vero voluptatem ex optio explicabo molestias! Unde id nemo consequatur culpa minus deleniti adipisci alias necessitatibus veniam asperiores repellendus ipsum ex ea, qui architecto provident ipsam totam quasi. Accusamus ullam voluptatibus aliquam voluptatum hic animi, quibusdam vero, deserunt, impedit quos facilis deleniti vel cumque ipsum maiores. Natus laudantium in laboriosam consequatur magni non possimus id impedit, aspernatur totam saepe perferendis provident incidunt nihil optio ratione porro dolor, praesentium numquam alias perspiciatis at. Incidunt aliquid cupiditate repellat deserunt expedita odio cumque, tempora impedit minus, consequatur laboriosam necessitatibus ullam reprehenderit sed minima dicta ipsam ex atque eveniet excepturi aperiam possimus. Debitis delectus nobis fugit cum repellat dolores nisi soluta, magnam, deleniti harum ratione suscipit deserunt porro. Minima natus commodi voluptatibus at ducimus debitis expedita velit sint aliquam vitae explicabo voluptate reprehenderit adipisci porro, eum repellat voluptatem autem. Est aperiam excepturi eos, dolorem, hic reiciendis sunt voluptatibus veniam repellendus blanditiis expedita, earum ullam dolor quisquam consectetur facere optio praesentium. Est cumque tenetur quae doloribus libero laudantium quod illum a ut. Minus tempore, incidunt quae ipsam temporibus debitis vero necessitatibus placeat doloremque, ea cum delectus nam distinctio officiis numquam architecto sed consectetur quibusdam. Ad quia minima itaque sit perspiciatis saepe earum accusantium veniam a sunt, deleniti odio incidunt fugit. Officia atque facilis odio exercitationem amet harum reiciendis a id quos quibusdam! Ut at neque, quasi est reprehenderit blanditiis doloremque eum esse quibusdam incidunt rem eligendi facere, quis placeat amet voluptatibus consequatur similique commodi sunt eveniet. Doloribus delectus id beatae officiis numquam ipsam dicta, eveniet ducimus? Quia excepturi quis rem quasi iusto. Iste repellendus officiis eum fugiat neque ipsum, dignissimos saepe placeat doloribus necessitatibus fugit sunt, eaque debitis quisquam unde!",
            author: "Leo",
        },
        {
            image: "../../assets/seven.jpg",
            date: "Tuesday, 11pm, EST 2024.01.24,",
            title:
                "This is going to the box heading we will have same size like top.",
            post: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores qui nam ratione sed fuga, tenetur minus, cumque praesentium dolorem numquam illo aliquam nostrum quod facilis vero voluptatem ex optio explicabo molestias! Unde id nemo consequatur culpa minus deleniti adipisci alias necessitatibus veniam asperiores repellendus ipsum ex ea, qui architecto provident ipsam totam quasi. Accusamus ullam voluptatibus aliquam voluptatum hic animi, quibusdam vero, deserunt, impedit quos facilis deleniti vel cumque ipsum maiores. Natus laudantium in laboriosam consequatur magni non possimus id impedit, aspernatur totam saepe perferendis provident incidunt nihil optio ratione porro dolor, praesentium numquam alias perspiciatis at. Incidunt aliquid cupiditate repellat deserunt expedita odio cumque, tempora impedit minus, consequatur laboriosam necessitatibus ullam reprehenderit sed minima dicta ipsam ex atque eveniet excepturi aperiam possimus. Debitis delectus nobis fugit cum repellat dolores nisi soluta, magnam, deleniti harum ratione suscipit deserunt porro. Minima natus commodi voluptatibus at ducimus debitis expedita velit sint aliquam vitae explicabo voluptate reprehenderit adipisci porro, eum repellat voluptatem autem. Est aperiam excepturi eos, dolorem, hic reiciendis sunt voluptatibus veniam repellendus blanditiis expedita, earum ullam dolor quisquam consectetur facere optio praesentium. Est cumque tenetur quae doloribus libero laudantium quod illum a ut. Minus tempore, incidunt quae ipsam temporibus debitis vero necessitatibus placeat doloremque, ea cum delectus nam distinctio officiis numquam architecto sed consectetur quibusdam. Ad quia minima itaque sit perspiciatis saepe earum accusantium veniam a sunt, deleniti odio incidunt fugit. Officia atque facilis odio exercitationem amet harum reiciendis a id quos quibusdam! Ut at neque, quasi est reprehenderit blanditiis doloremque eum esse quibusdam incidunt rem eligendi facere, quis placeat amet voluptatibus consequatur similique commodi sunt eveniet. Doloribus delectus id beatae officiis numquam ipsam dicta, eveniet ducimus? Quia excepturi quis rem quasi iusto. Iste repellendus officiis eum fugiat neque ipsum, dignissimos saepe placeat doloribus necessitatibus fugit sunt, eaque debitis quisquam unde!",
            author: "little soldier",
        },
        {
            image: "../../assets/seven.jpg",
            date: "Tuesday, 11pm, EST 2024.01.24,",
            title:
                "This is going to the box heading we will have same size like top.",
            post: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores qui nam ratione sed fuga, tenetur minus, cumque praesentium dolorem numquam illo aliquam nostrum quod facilis vero voluptatem ex optio explicabo molestias! Unde id nemo consequatur culpa minus deleniti adipisci alias necessitatibus veniam asperiores repellendus ipsum ex ea, qui architecto provident ipsam totam quasi. Accusamus ullam voluptatibus aliquam voluptatum hic animi, quibusdam vero, deserunt, impedit quos facilis deleniti vel cumque ipsum maiores. Natus laudantium in laboriosam consequatur magni non possimus id impedit, aspernatur totam saepe perferendis provident incidunt nihil optio ratione porro dolor, praesentium numquam alias perspiciatis at. Incidunt aliquid cupiditate repellat deserunt expedita odio cumque, tempora impedit minus, consequatur laboriosam necessitatibus ullam reprehenderit sed minima dicta ipsam ex atque eveniet excepturi aperiam possimus. Debitis delectus nobis fugit cum repellat dolores nisi soluta, magnam, deleniti harum ratione suscipit deserunt porro. Minima natus commodi voluptatibus at ducimus debitis expedita velit sint aliquam vitae explicabo voluptate reprehenderit adipisci porro, eum repellat voluptatem autem. Est aperiam excepturi eos, dolorem, hic reiciendis sunt voluptatibus veniam repellendus blanditiis expedita, earum ullam dolor quisquam consectetur facere optio praesentium. Est cumque tenetur quae doloribus libero laudantium quod illum a ut. Minus tempore, incidunt quae ipsam temporibus debitis vero necessitatibus placeat doloremque, ea cum delectus nam distinctio officiis numquam architecto sed consectetur quibusdam. Ad quia minima itaque sit perspiciatis saepe earum accusantium veniam a sunt, deleniti odio incidunt fugit. Officia atque facilis odio exercitationem amet harum reiciendis a id quos quibusdam! Ut at neque, quasi est reprehenderit blanditiis doloremque eum esse quibusdam incidunt rem eligendi facere, quis placeat amet voluptatibus consequatur similique commodi sunt eveniet. Doloribus delectus id beatae officiis numquam ipsam dicta, eveniet ducimus? Quia excepturi quis rem quasi iusto. Iste repellendus officiis eum fugiat neque ipsum, dignissimos saepe placeat doloribus necessitatibus fugit sunt, eaque debitis quisquam unde!",
            author: "little soldier",
        },
        {
            image: "../../assets/seven.jpg",
            date: "Tuesday, 11pm, EST 2024.01.24,",
            title:
                "This is going to the box heading we will have same size like top.",
            post: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores qui nam ratione sed fuga, tenetur minus, cumque praesentium dolorem numquam illo aliquam nostrum quod facilis vero voluptatem ex optio explicabo molestias! Unde id nemo consequatur culpa minus deleniti adipisci alias necessitatibus veniam asperiores repellendus ipsum ex ea, qui architecto provident ipsam totam quasi. Accusamus ullam voluptatibus aliquam voluptatum hic animi, quibusdam vero, deserunt, impedit quos facilis deleniti vel cumque ipsum maiores. Natus laudantium in laboriosam consequatur magni non possimus id impedit, aspernatur totam saepe perferendis provident incidunt nihil optio ratione porro dolor, praesentium numquam alias perspiciatis at. Incidunt aliquid cupiditate repellat deserunt expedita odio cumque, tempora impedit minus, consequatur laboriosam necessitatibus ullam reprehenderit sed minima dicta ipsam ex atque eveniet excepturi aperiam possimus. Debitis delectus nobis fugit cum repellat dolores nisi soluta, magnam, deleniti harum ratione suscipit deserunt porro. Minima natus commodi voluptatibus at ducimus debitis expedita velit sint aliquam vitae explicabo voluptate reprehenderit adipisci porro, eum repellat voluptatem autem. Est aperiam excepturi eos, dolorem, hic reiciendis sunt voluptatibus veniam repellendus blanditiis expedita, earum ullam dolor quisquam consectetur facere optio praesentium. Est cumque tenetur quae doloribus libero laudantium quod illum a ut. Minus tempore, incidunt quae ipsam temporibus debitis vero necessitatibus placeat doloremque, ea cum delectus nam distinctio officiis numquam architecto sed consectetur quibusdam. Ad quia minima itaque sit perspiciatis saepe earum accusantium veniam a sunt, deleniti odio incidunt fugit. Officia atque facilis odio exercitationem amet harum reiciendis a id quos quibusdam! Ut at neque, quasi est reprehenderit blanditiis doloremque eum esse quibusdam incidunt rem eligendi facere, quis placeat amet voluptatibus consequatur similique commodi sunt eveniet. Doloribus delectus id beatae officiis numquam ipsam dicta, eveniet ducimus? Quia excepturi quis rem quasi iusto. Iste repellendus officiis eum fugiat neque ipsum, dignissimos saepe placeat doloribus necessitatibus fugit sunt, eaque debitis quisquam unde!",
            author: "little soldier",
        },
        {
            image: "../../assets/relaxcode.jpg",
            date: "Tuesday, 11pm, EST 2024.01.24,",
            title:
                "This is going to the box heading we will have same size like top.",
            post: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores qui nam ratione sed fuga, tenetur minus, cumque praesentium dolorem numquam illo aliquam nostrum quod facilis vero voluptatem ex optio explicabo molestias! Unde id nemo consequatur culpa minus deleniti adipisci alias necessitatibus veniam asperiores repellendus ipsum ex ea, qui architecto provident ipsam totam quasi. Accusamus ullam voluptatibus aliquam voluptatum hic animi, quibusdam vero, deserunt, impedit quos facilis deleniti vel cumque ipsum maiores. Natus laudantium in laboriosam consequatur magni non possimus id impedit, aspernatur totam saepe perferendis provident incidunt nihil optio ratione porro dolor, praesentium numquam alias perspiciatis at. Incidunt aliquid cupiditate repellat deserunt expedita odio cumque, tempora impedit minus, consequatur laboriosam necessitatibus ullam reprehenderit sed minima dicta ipsam ex atque eveniet excepturi aperiam possimus. Debitis delectus nobis fugit cum repellat dolores nisi soluta, magnam, deleniti harum ratione suscipit deserunt porro. Minima natus commodi voluptatibus at ducimus debitis expedita velit sint aliquam vitae explicabo voluptate reprehenderit adipisci porro, eum repellat voluptatem autem. Est aperiam excepturi eos, dolorem, hic reiciendis sunt voluptatibus veniam repellendus blanditiis expedita, earum ullam dolor quisquam consectetur facere optio praesentium. Est cumque tenetur quae doloribus libero laudantium quod illum a ut. Minus tempore, incidunt quae ipsam temporibus debitis vero necessitatibus placeat doloremque, ea cum delectus nam distinctio officiis numquam architecto sed consectetur quibusdam. Ad quia minima itaque sit perspiciatis saepe earum accusantium veniam a sunt, deleniti odio incidunt fugit. Officia atque facilis odio exercitationem amet harum reiciendis a id quos quibusdam! Ut at neque, quasi est reprehenderit blanditiis doloremque eum esse quibusdam incidunt rem eligendi facere, quis placeat amet voluptatibus consequatur similique commodi sunt eveniet. Doloribus delectus id beatae officiis numquam ipsam dicta, eveniet ducimus? Quia excepturi quis rem quasi iusto. Iste repellendus officiis eum fugiat neque ipsum, dignissimos saepe placeat doloribus necessitatibus fugit sunt, eaque debitis quisquam unde!",
            author: "little soldier",
        },
        {
            image: "../../assets/relaxcode.jpg",
            date: "Tuesday, 11pm, EST 2024.01.24,",
            title:
                "This is going to the box heading we will have same size like top.",
            post: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores qui nam ratione sed fuga, tenetur minus, cumque praesentium dolorem numquam illo aliquam nostrum quod facilis vero voluptatem ex optio explicabo molestias! Unde id nemo consequatur culpa minus deleniti adipisci alias necessitatibus veniam asperiores repellendus ipsum ex ea, qui architecto provident ipsam totam quasi. Accusamus ullam voluptatibus aliquam voluptatum hic animi, quibusdam vero, deserunt, impedit quos facilis deleniti vel cumque ipsum maiores. Natus laudantium in laboriosam consequatur magni non possimus id impedit, aspernatur totam saepe perferendis provident incidunt nihil optio ratione porro dolor, praesentium numquam alias perspiciatis at. Incidunt aliquid cupiditate repellat deserunt expedita odio cumque, tempora impedit minus, consequatur laboriosam necessitatibus ullam reprehenderit sed minima dicta ipsam ex atque eveniet excepturi aperiam possimus. Debitis delectus nobis fugit cum repellat dolores nisi soluta, magnam, deleniti harum ratione suscipit deserunt porro. Minima natus commodi voluptatibus at ducimus debitis expedita velit sint aliquam vitae explicabo voluptate reprehenderit adipisci porro, eum repellat voluptatem autem. Est aperiam excepturi eos, dolorem, hic reiciendis sunt voluptatibus veniam repellendus blanditiis expedita, earum ullam dolor quisquam consectetur facere optio praesentium. Est cumque tenetur quae doloribus libero laudantium quod illum a ut. Minus tempore, incidunt quae ipsam temporibus debitis vero necessitatibus placeat doloremque, ea cum delectus nam distinctio officiis numquam architecto sed consectetur quibusdam. Ad quia minima itaque sit perspiciatis saepe earum accusantium veniam a sunt, deleniti odio incidunt fugit. Officia atque facilis odio exercitationem amet harum reiciendis a id quos quibusdam! Ut at neque, quasi est reprehenderit blanditiis doloremque eum esse quibusdam incidunt rem eligendi facere, quis placeat amet voluptatibus consequatur similique commodi sunt eveniet. Doloribus delectus id beatae officiis numquam ipsam dicta, eveniet ducimus? Quia excepturi quis rem quasi iusto. Iste repellendus officiis eum fugiat neque ipsum, dignissimos saepe placeat doloribus necessitatibus fugit sunt, eaque debitis quisquam unde!",
            author: "little soldier",
        },
        {
            image: "../../assets/relaxcode.jpg",
            date: "Tuesday, 11pm, EST 2024.01.24,",
            title:
                "This is going to the box heading we will have same size like top.",
            post: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores qui nam ratione sed fuga, tenetur minus, cumque praesentium dolorem numquam illo aliquam nostrum quod facilis vero voluptatem ex optio explicabo molestias! Unde id nemo consequatur culpa minus deleniti adipisci alias necessitatibus veniam asperiores repellendus ipsum ex ea, qui architecto provident ipsam totam quasi. Accusamus ullam voluptatibus aliquam voluptatum hic animi, quibusdam vero, deserunt, impedit quos facilis deleniti vel cumque ipsum maiores. Natus laudantium in laboriosam consequatur magni non possimus id impedit, aspernatur totam saepe perferendis provident incidunt nihil optio ratione porro dolor, praesentium numquam alias perspiciatis at. Incidunt aliquid cupiditate repellat deserunt expedita odio cumque, tempora impedit minus, consequatur laboriosam necessitatibus ullam reprehenderit sed minima dicta ipsam ex atque eveniet excepturi aperiam possimus. Debitis delectus nobis fugit cum repellat dolores nisi soluta, magnam, deleniti harum ratione suscipit deserunt porro. Minima natus commodi voluptatibus at ducimus debitis expedita velit sint aliquam vitae explicabo voluptate reprehenderit adipisci porro, eum repellat voluptatem autem. Est aperiam excepturi eos, dolorem, hic reiciendis sunt voluptatibus veniam repellendus blanditiis expedita, earum ullam dolor quisquam consectetur facere optio praesentium. Est cumque tenetur quae doloribus libero laudantium quod illum a ut. Minus tempore, incidunt quae ipsam temporibus debitis vero necessitatibus placeat doloremque, ea cum delectus nam distinctio officiis numquam architecto sed consectetur quibusdam. Ad quia minima itaque sit perspiciatis saepe earum accusantium veniam a sunt, deleniti odio incidunt fugit. Officia atque facilis odio exercitationem amet harum reiciendis a id quos quibusdam! Ut at neque, quasi est reprehenderit blanditiis doloremque eum esse quibusdam incidunt rem eligendi facere, quis placeat amet voluptatibus consequatur similique commodi sunt eveniet. Doloribus delectus id beatae officiis numquam ipsam dicta, eveniet ducimus? Quia excepturi quis rem quasi iusto. Iste repellendus officiis eum fugiat neque ipsum, dignissimos saepe placeat doloribus necessitatibus fugit sunt, eaque debitis quisquam unde!",
            author: "little soldier",
        },
        {
            image: "../../assets/relaxcode.jpg",
            date: "Tuesday, 11pm, EST 2024.01.24,",
            title:
                "This is going to the box heading we will have same size like top.",
            post: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores qui nam ratione sed fuga, tenetur minus, cumque praesentium dolorem numquam illo aliquam nostrum quod facilis vero voluptatem ex optio explicabo molestias! Unde id nemo consequatur culpa minus deleniti adipisci alias necessitatibus veniam asperiores repellendus ipsum ex ea, qui architecto provident ipsam totam quasi. Accusamus ullam voluptatibus aliquam voluptatum hic animi, quibusdam vero, deserunt, impedit quos facilis deleniti vel cumque ipsum maiores. Natus laudantium in laboriosam consequatur magni non possimus id impedit, aspernatur totam saepe perferendis provident incidunt nihil optio ratione porro dolor, praesentium numquam alias perspiciatis at. Incidunt aliquid cupiditate repellat deserunt expedita odio cumque, tempora impedit minus, consequatur laboriosam necessitatibus ullam reprehenderit sed minima dicta ipsam ex atque eveniet excepturi aperiam possimus. Debitis delectus nobis fugit cum repellat dolores nisi soluta, magnam, deleniti harum ratione suscipit deserunt porro. Minima natus commodi voluptatibus at ducimus debitis expedita velit sint aliquam vitae explicabo voluptate reprehenderit adipisci porro, eum repellat voluptatem autem. Est aperiam excepturi eos, dolorem, hic reiciendis sunt voluptatibus veniam repellendus blanditiis expedita, earum ullam dolor quisquam consectetur facere optio praesentium. Est cumque tenetur quae doloribus libero laudantium quod illum a ut. Minus tempore, incidunt quae ipsam temporibus debitis vero necessitatibus placeat doloremque, ea cum delectus nam distinctio officiis numquam architecto sed consectetur quibusdam. Ad quia minima itaque sit perspiciatis saepe earum accusantium veniam a sunt, deleniti odio incidunt fugit. Officia atque facilis odio exercitationem amet harum reiciendis a id quos quibusdam! Ut at neque, quasi est reprehenderit blanditiis doloremque eum esse quibusdam incidunt rem eligendi facere, quis placeat amet voluptatibus consequatur similique commodi sunt eveniet. Doloribus delectus id beatae officiis numquam ipsam dicta, eveniet ducimus? Quia excepturi quis rem quasi iusto. Iste repellendus officiis eum fugiat neque ipsum, dignissimos saepe placeat doloribus necessitatibus fugit sunt, eaque debitis quisquam unde!",
            author: "little soldier",
        },
    ];
};

export const fetchOnePost = async (id) => {
    return await fetch(`${fetchedURL}/${id}?_embed`)
        .then((res) => res.json())
        .then((post) => {
            if (
                post._embedded &&
                post._embedded["wp:featuredmedia"] &&
                post._embedded["wp:featuredmedia"][0]
            ) {
                return {
                    ...post,
                    title: post.title.rendered,
                    excerpt: post.excerpt.rendered,
                    image: post._embedded["wp:featuredmedia"][0].source_url,
                    author: post._embedded.author[0].name,
                };
            }
            return {
                ...post,
                title: post.title.rendered,
                excerpt: post.excerpt.rendered,
                image: "",
                author: post._embedded.author[0].name || "",
            };
        });
};
